---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 24h
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.27.x"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  targetNamespace: cnpg-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nodeSelector:
      hardware.home/tier: performance
    webhook:
      livenessProbe:
        failureThreshold: 10
        timeoutSeconds: 30
      readinessProbe:
        failureThreshold: 10
        timeoutSeconds: 30
