apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media-management
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:XVs5TDQpSks30gugAgYRMcy8p01iU8jWD682kAyaFNw=,iv:KTSkN/6LwsqZ3P5ncvshSYJOGzOsaXZ5GhpRnLrY0q4=,tag:Fhp4nSvTbcVotIyoGbFztw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:uQl73a6eJZ35UDwzM3QGj+7GBhM6eO/udFle8jhYIMg=,iv:qUug2QKxup/Ajo0JVFKKfx68YF+vm1it1K1Mvk7LoLA=,tag:kvFq7Q8z0i6nNuxeX3eFgg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdk1qcmJ1NFRBeWduYk9l
            U09yVEtCVUJKTzcyZ1RzVW1Gd1BPN2xhakdrCkwwSU5KKzU4N1N2Nmxxc1lKcmdR
            K25UU2Nlb2NSSkg1cEplSkVrcUFOeWcKLS0tICtTYUw3QnlFcUtYbW9LNTBnSnQy
            WHlNalJOb3oyS3lHMVo1cHZrSXBnaGMKHtmEbzfPdyLiwp+jiN69TeToH4uKlPtA
            wEyMIo0dakPZV3Q24Fp9WQT7pZTDkVIQK2zC9RUO8OE3Jvx1JNY9yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:01:28Z"
    mac: ENC[AES256_GCM,data:I1Ysl/L2B8rE3RvamXEETqDWR7SpgM4e5o8P0+kqShgIvMeXL6w+ZaWrHtdk7btynfNV7lzu9k8keAYvQIFc9CKa7AlWDXXZaoLfq/vZPD0u0TtYPejguV05HUNgBBAtovMcZ+uMrLO0NhufC3yMsTUMcuhWK3Y5VDDs600VFRI=,iv:yfOrA5kMdWnaAqZsP8IX4CjyDXOAub+xdjv/+jqeFv4=,tag:UnEcW6QgiqKr0hJvvmy+rQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
