apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media-management
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:HSe354OXH3Z1gtjlbk1/gfCrVK95GBE9CY/vOMIuhSg=,iv:9YqY1tuquIwFbJHZr8nzPdFBtpqPkwlIWeXD5mrYIVM=,tag:o33t1RpoUrpfd/JZCLNSpw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:lLDPx87D1IhmahgLfzPTDDIIx6AE5tcKWBE+VuDRcSk=,iv:+5rYBQbdlf6I+jZVzJU+Eo9CLE3by7HMXQ4YjgGZhUY=,tag:mE7xoiYSn4dAd3bWaOl8Kw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZkEzOTFuQzBrNTBGUU5Q
            aXA1VGZrRWlkV1JSa1lPNDRmRlpyOWZLSGlZCkN3blN1bkVCb2wxNnlqZGhva0Ey
            d0orWnRmMDJFZUFUbkZTSlRuY2ZYRzgKLS0tIDN6ZEJFNldZNW1Ib29jTWIyQnJw
            T2pwSTB3MVpwcHIvU3V4aVRmc0VJY2cKGI7zYgrpbdc5ZgEnLIcJ1ForIkwt834p
            FNpVYdsa2S5nQ5m53WIJSoxkHV6zqLCGCJumSQel2/Cm+pAVy/x0Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:r/9YGFZe0C/0txWRcZUZiXt6rJvZjrLf1ORNqeMkXubLHm5GUNwPHl9rF3AnIolij6WWWjUXS0VpLtBZOO5fO1dEtsUxd/Zm+1M8s3ICKheqlXHoNsk49B6QY9Wjh41+bsNMQ5Segptc7zp2QkWh5xU6EeEN5Vsvdt8uyhMpLy0=,iv:IWIC3o9z13gA2rQa+LpFRcXgRIubnOxUaFoHDNFwlq4=,tag:y8FdMsVeg6iqsYIiH7z/qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
