apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media-management
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:uws+G6r0RYPfa+N9U+Eb7kjPBkUQDu1o4l0hSWx9pqk=,iv:eW05k9+U16RJKM4tz4n/smz65h6HlNvrmweixE1IgRk=,tag:3OteMiunQhlWiNDCwGZ6PA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:0Fwo2dvvdblGLBkaHU+QArIuBfZH7kfNOdZOpvZ/fFg=,iv:c91FRdHrcRYteOwn/8pL984A1YabR9Kzu92RM5xMCxA=,tag:VSb78/Jw2XhtjBzoExLFzQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZUVZd3pWMCt1aW1oQ0sr
            cXJKWUpIeGpQck5HNkQzbi83TmpLZE5VaVQwCmhKVjE3ZTN3UXJZbkplNXNzME9w
            dm53NGFWUXNVWEVjL29YR2JhRGlFK28KLS0tIG1hMVhjTW1EODRnZ1Rrai9wZE5W
            cXpJUDdUT0RIRFhuN1VySlJ2WVllQlEK8uSsy1HY8h9+b222Knuf06H+vP/L9Knw
            fuVL4ItAYe2VSgr0WEHJLyyc8SNW4nXzP+vfG+lZMxAL7hAHaYpbFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:vKHkyptUh0PU5XWx09NnzKAuoXKRn6wHhdFvRX12VVyLShNqvcveXKCWIMe+gGEMFDGI93thjBo9zo/zb3wnX4bqbalUa3llYxQ/bITS0t1EhjEuSZ8gNxGu1QclHPVXZg2175I7nyKwxXKWytKpKksAJk5439LczNnnTC4p7Uo=,iv:SQA0ryrRTbtNyXUEBYf11Z7zWIZRc3BJwPAjXsKxWa4=,tag:YgNQW8QYlRSvz2LeSsRLzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
