apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:1QW1lYCb39eIiTAwBhwrRrhGfWGANqi5N6fwMILWGVwbcz6GxuqG9rAC8tk=,iv:Hso8AkNY2bXbCru5nnoWksS32E+VRf4xKbvHrz+Mb2s=,tag:poQZiyGd82Hin/4+mfPKrQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:krYFIxiMaMh5VynH+kma950ck/M+Hnz9yW3+AlSWj7VsF1OS/naOyYJ6d3w=,iv:s3Ug7Kqpdw081MatBZ/BN9ZpDoOHyKHfiBIpPdhRWR8=,tag:nl33rB9/IMbrqzztmSfH/w==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:AizH8QGQpd8FXcVI5x5IJg==,iv:3bwQl46wPw6o8pZUIMxCAPZqVVFI6xr+HwdTeIwRDzk=,tag:DCnHF2hTmGaS3W/o8AdUSw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:vUIxVu/QdFBWK+CJ4gCwQMQ=,iv:Lyd2Agu02GlM53IwIV69oZea1UCkwNVkUqFqikpe9gI=,tag:yb7wElKbucwOPy40mqpZUg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSS8rL24ycTBXam0zY3hy
            MnZsSnQyV2hrSmhkQkl3RnQ1VzM4OTBIWENZCkdlTGN6WXc3UTF5c00veTNETGZ2
            Y2t3YU9iUUF0MWZ0d3F2S0JCRU0wUWsKLS0tIHozK0Y4cTVPM0FmL09aU2VCV0Ew
            aG1jVTRyMktEWVlJb2dFLzZwOWVNdmMKgaqgY+E2DdReydGkPzDFNkI9mrdw2Qwa
            VFp6/x91BSdMdp8EkG9dENiAB3fHb4M6molSGEmp+0Jn7WkgZkVngw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T10:52:26Z"
    mac: ENC[AES256_GCM,data:yF8J4ibX1MvEriUXryXJnKD+H7jH4ALQnCOpJxVQzi7ELlV2jtgW9WnbXhkbIcwfPjMiuO0Sh7LnsU5Gn4gkz4xTmgpiW9Z1UA2sY+407M/ApmN0ue5mE9Muorl+GG9l1PAW56sN5BfrQ8RKIPPtUGZWNsM3DcvHHUly5kijVmI=,iv:KBtUBMkTK2qPY/l6QH+iy8szCqifqPaGU+y1yePVBH0=,tag:T+RTI/3DDebTsN8933MKpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
