apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:PvISsxuBnTj+M5IeDcGTqb651kdZKc422SgN5G8N+xpkU7cL6hqKAcC9I2Y=,iv:JWGGWWvMkNDhiAURkF4kCkG7Potdr8xIpgYrtgNyZPA=,tag:L8uT5Y8r3560uMIqgoKj2w==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:LR8lGFDDZFPRJHKYWkzh9NZLuRlQ6PQ81t7gqaG6WhwXGBVT6MhqKPjp9Vk=,iv:j8xKp74ZOpF5jS07WNhw/s5kUovwS/6Ce28XeQUXXYY=,tag:Yfdmb8T23eHkN40A2Tko0A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:csn/SMxr2g/dnyKVXRePrA==,iv:ykiR1DZZeJmzqR4Gbs6Z8BpOcKyjkPokiBGHQnY+FMY=,tag:4ZA/1Fa3V06huO1XaH6Trw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:9iCax8LNVTyLBVpCNWiG8g0=,iv:333dVSXcXzQ1wW3ROj+X3GnBsKqQwn1slGbbScML+ac=,tag:poeCY2o9YjRB7KX1fJTiKA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dnFDUXBvQldMbUpkV0hV
            cVF3Tzg3WkRPa3E3TW1uS0o0LzUzT09La3pFClBTcFNCQlFzWUVwbFUyN2hzUXJQ
            RFRnNitNWGdLZ1o2cFpmcVFBYUdSVGcKLS0tIEpMVnpBRkpFWUh5eisrZG5pcDlB
            MnJqc0ZaS3g0VXRMK21QN1p2SjA4bVkK5Dv7uftEQ5e3XQJhJ+cA0eey9N7zFzuj
            65poT+HLKjBQGMfzry7DNRqIGYCFXTYazN5oZGfNovVmNWwZIvlljQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:45:54Z"
    mac: ENC[AES256_GCM,data:ZJEE5A/HK42ncR26g1J1fDFCjnl1R8vCi1ZAFDCBwjRukq17lbiw6RWtcLFu+Le8j6F8MSwDlvXAG9FQ/07c2qg4HL2arXbzXP9ZtK4fJKrAJoLpD950hp6cPczSHLSEa8VghCsgQuK+iX6fGI/S3T4T1YM2UZhZvUlGEL42+W0=,iv:s7LaOCq9ifAvR+JJ1a3hc3pmQg3ZS5818OjeYkmiUD8=,tag:XtAteBrThiiX7bnvalTXBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
