apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ZS6j/i0s5IrjE6Xafo4wIvQiBZBAgHHX03/rcZrJN466KErfJo9TE15TvCE=,iv:Q9IS2+9fFu0ybYXWl2kmmWzbrp2H5aqyDBUhBgOfdAA=,tag:AtYwQRJU5b+DjEc82ZcGmQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:pqJCjq2vSelwcBTsLcROh1L87Ps0l1+q4n0NQ5rnSbCFo7ebO59ebIutJtU=,iv:lXsvoEGvSVp+L423ETUYPLbPBBlU4/hVoM/Ep9t8CJc=,tag:t0098UdbpfIOFf/EBUATjA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:AzjxmxdM1X2fTeEpYnn/dQ==,iv:ePI/0vXEN0WUiaA4/86xUPRbKJj3EUEhLgVeFwqV95Y=,tag:qE2UH0TgQ0+GBjEwhxBToA==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:Vvt8Qfe0RJz96va5J3WIlrA=,iv:rlT03uJwF3bRns3nH8RhQFBwfPesjh+WMJJGsT1O/cI=,tag:xrv7MNie43tKmzcNvwwodw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseWRYakFudTdJZ1g3VXZz
            R3BzeklwR0FZSHl5VTdjZkxuOWg1cTRUUEdFCmZpNW1hSkk5WERYd2lzaUI1eEIw
            SlNXSkVXaSt1ekozVVEvWGR5R3h0TzQKLS0tIEZ0SXg4L2hIY0RBcDNMOWduWDZy
            MDZhL3hISEROaUFtVk00NkcyaWp6aGsKnIiJQjdFfHjO20GD46UVoT89Rlw2+S5K
            I6dIRQn/O5y2qnFNnZLXjmyWtUCzxFWN4oIr4vto/Fa3OkHgJOmnIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:jiFz/JsPKirnwyA87VXNRUrhxk0lQJZOlXgQ2L331fsMZ3qI6lZa4q5WYyaNdPbNwl7gT5SsP9FlC4Ds3jWZ4Cj/q0MME1kCByIcXeIUZ24HsRTwJ1w2S0aOiUu81oKStB2vW5ezEdDkskYj2CQM26S160KbnfFY7n4uQty+QLY=,iv:c998IOkCXKMvecUqnqDEpKt1bF30Mi11cGilgR3cCms=,tag:5Ut1EqY36ahIAY1XpNkWPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
