services:
  tdarr:
    image: haveagitgat/tdarr:latest
    ports:
      - "8265:8265" # webUI port
      - "8266:8266" # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false # set to true if you want this container to encode/decode media
      - inContainer=true
      - ffmpegVersion=7
      - auth=true
      - maxLogSizeMB=10
      - cronPluginUpdate=
    volumes:
      - /opt/docker/tdarr/server:/app/server
      - /opt/docker/tdarr/configs:/app/configs
      - /opt/docker/tdarr/logs:/app/logs
      - ${MEDIA_PATH}:/data
      - /opt/docker/tdarr/transcode_cache:/temp
    networks:
      - tdarr_net
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
      labels:
        - "caddy=tdarr.home"
        - "caddy.reverse_proxy={{upstreams 8265}}"

networks:
  tdarr_net:
    driver: overlay
    attachable: true
