services:
  pms:
    image: lscr.io/linuxserver/plex:latest
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    environment:
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /opt/docker/plex/config:/config
      - ${MEDIA_PATH}:/data:ro
    networks:
      - plex_net
      - proxy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        caddy: http://plex.home
        caddy.reverse_proxy: "{{upstreams 32400}}"
      placement:
        constraints:
          - node.role == manager
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/docker/tautulli/config:/config
    ports:
      - "8181:8181"
    networks:
      - plex_net
      - proxy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        caddy: http://tautulli.home
        caddy.reverse_proxy: "{{upstreams 8181}}"
      placement:
        constraints:
          - node.role == manager

networks:
  plex_net:
    driver: overlay
    attachable: true
  proxy-net:
    external: true
    name: proxy-net
