apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:eBs3/OxifWeTS6HdKrAupczesjmssYma9956kp0U/+5XdDepZmUL/X4BHbM=,iv:CxQYZJINj0xBUWn0aXLcOc/oMxrFUocN9lWMs+7i+v4=,tag:lVq3/oYdEDwIgwvJkRemwA==,type:str]
    secret_key: ENC[AES256_GCM,data:Far66OflVLB2mVxjL2K1yN414ODK3Y0MIoWwGSXDI9s=,iv:1kX8x1RI6mOFfnKtFkSlvA5myf9Z77Jub0pwoW2CWoI=,tag:8Kx6YPhbSpgMoQ48aHlxzw==,type:str]
    resend_api_key: ENC[AES256_GCM,data:lRgkGpFfrQ41oBKqe2vm3B4STNQXGD49DByQ4erv0UgFieWw,iv:zeUoWPdUXe9VX7nUvZePv/K4PbrFGlq76VKdiQQWiZ4=,tag:rrNhwvaSY0L9WptcFL1BcA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMXdKcWxpMkU3Y2RNb01K
            d3JsM25ETEZLUjY4NDRuRWlLL1dTN2w1UldJCkFwWk9SdlJWNTBYWko4R2F1UkxN
            a3RRa2orTHFVWlU0NmpjUC9uSC82anMKLS0tIFU4WTFhSFNUek9TdkZMZGlmcHk1
            TDArVnZGdG90cVRJdGx5TnNHdFNhNk0KM+7oEvZTst5Fnk0Y/Hd8ZEaXOo2SKgEl
            g4Ok4jnMOker7HLa3dgWTfnT3fyMX7NvX/SdTxOsV6bF/xLO3qpFUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:xggXpp28fitnS9iiMp1r7AaI1J0puSqfUXgjiwrKD3ko3oWlkdaoSjUMNQLsAzAFPjG8NxAMAwteQi5MdBnfosz/m9YbJmp7qQwKwTNY4I0c9v4eZDJuxGT3Vcl07wACjA3L+3x/29C0jHrCupS71rs6FP7uVksiLx4EJlNSfAY=,iv:aRH+Y0FRgoiCILdM2AKJCmr6sf9u8ayEf8+BXlM0zNs=,tag:CzD/jTgFSTrSZVmM+FeoRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
