apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:xKw+bA5fCVuZFVFV1k3mTkzUfW1W/zaegodJIw4JsZX3k914IiFu0PMy7rE=,iv:JMTpB1A6mgTZb7Xo8bYJ1NRGrscbg0TzQFTxcl9rFdw=,tag:7b6xFVD4M75ktHHxpHBMIg==,type:str]
    secret_key: ENC[AES256_GCM,data:TrlMFkLwmvG97Zts6l4ECG6/Y+/rnWl7BWeUMbxOdg8=,iv:v23xjgjl+QnOBmoEO4DtAqxKJJHxmzHGCLQwymzpkKs=,tag:rFqJjElWPjrF7hw6XP/lwg==,type:str]
    resend_api_key: ENC[AES256_GCM,data:srsTevH4Q4Wk/hBpqA/uKP3I695NKO/93djsuwcS3JQyQ7MT,iv:jC1xjoEkfqLfZHUn0A8xi4Kxwra/jTi6tUVR5DsWq+c=,tag:51nCHs2Lars40AUm12bwLg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNkNvL2tBVHJMak10c0Fy
            MzVEY2JyQjIvMG13OXEwMGN3YVd6Sk5pVFY0CnBkZGFZcW4rUFhKQis4b1haTWxR
            VGlDQnAyeXZ0NFRDVVR0UE0xeWIrcmsKLS0tIGhkbzRIb2NramFqUzBram1wbG9l
            N1UvZkhDdmYwV0h1WkR1Y0VFMmN3SVUKY5kkyIu8kLFq64M75bbNtMNUMkTyIgma
            AboLpNvqtFVIty4F7+Hfiav0PhZBwcqR9gJvWF8yo5pFqx5nwyGvbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:01:28Z"
    mac: ENC[AES256_GCM,data:tSG89pIViQIFf5ZHkPfcFXwOl9n6gG/BNjG6zdwmORr0iwX4xJ3enBLUMVFoMLQb84VdMvAmpm9pCl4hz+AoYOwZOW5CvbX86OumMwNcPAEGFx0xAryE1q+CWJPVqHI+oLTTA4zW0LcMrFqb//hIcTN1PglrFhGLpFczTddwOww=,iv:6xynxuR6Vrfcx65JLqTHoeYw+4fBPfCgo7Uvpmn6F08=,tag:65EuCQ05iO0zxG0ALGSUTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
