apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:PeIrBad0Dtxd5IMqnHyEFaYE5JocJLy1TWggG3vrx70t+hPDip9+74sZjp4=,iv:OyzgimnOZSUfbxdK6wZoykXdzh3BX49lyZCCZ5T+bJI=,tag:Cu6GwXo2pD1DSA0DN8mxnw==,type:str]
    secret_key: ENC[AES256_GCM,data:AqT1OTfqxjSeA/vPX0aP+ie/vFovtx+Zn6iHigsnXUE=,iv:jZ0HTsjEwpfupEQ9iYHmgEfnbhyKjy/Gwz+PvMYzAQM=,tag:0PdVg5luIBEX0m7AIItwBQ==,type:str]
    resend_api_key: ENC[AES256_GCM,data:EmXwFaRC4n2SNiAIBUIHqJJcacDez5PhrLomhIaEeZMuUhmW,iv:vHOTJEkg9iKSgRA78Xm5SrQr6F7ibNY/iaSTtbAtEZc=,tag:BtUWakotW8s5mdfoGgrmXQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOG5lQ3FuQ0RiL01URVRr
            cU5lbTdnYk5hNXVReVJWRi93Zlo0MHZ0Mkd3Cm4wUm5oTW9xUFdJYUpQT2c2U3Vq
            V2d3L3QxWnp1UWVwOFZqTWRVdFFCemMKLS0tIExBZWUvUTAvd3lYYkM0QStSVUtN
            NlMvR3QyZW5iQU84UmJLZHFCWERQQXcKYDn2l5RvDLnsChkhaLgw8TX2nH8IP8Ui
            PNUpHbS+DyOKoFP3Fs3nPKR/yf3sAsirff37fI0Tb2LxNgIdM6A8tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:59:36Z"
    mac: ENC[AES256_GCM,data:gOY9AJC12xaROfuL/DsRG3zOhwyxlpHJGYH4Y605fuPwXn0QRrR2hWSGwraLKqPoEJ1Dk+PQAC9ExyX7sH7PkuRcbqFlzMw02T0r2VNKeduYAS1nsteY3IO7fR96dh4jDxq30W+pQeiCXrbtWeREHx0ztaB/8Y7RUeDCXbzthG8=,iv:pGQ5fRlF6smwdwCxUoYUBN+ZUUwc0/7v874dQCY1nFo=,tag:5qJSzjMmJx23fNC4Hq+wUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
