---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-outpost
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      services:
        - name: ak-outpost-traefik-proxy-outpost
          port: 9000
