apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-jellyseerr
  namespace: jellyseerr
spec:
  redirectRegex:
    regex: '^https?://jellyseerr\.(.+)'
    replacement: "https://seerr.${1}"
    permanent: true
