---
apiVersion: v1
kind: ConfigMap
metadata:
  name: net-config
  namespace: homelab
data:
  TZ: "Europe/Warsaw"
  TAILSCALE_ROUTES: "192.168.0.0/24"
  TS_STATE_DIR: "/var/lib/tailscale"
  TS_USERSPACE: "false"
  TS_EXTRA_ARGS: "--snat-subnet-routes=true --accept-dns=false"
