---
# AdGuard work PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-work
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
# AdGuard conf PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-conf
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
# Tailscale state PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tailscale-state
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
