apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:HdKsgNnaiw6ixgPoRFRCs2T+jRi0ZNTa9A4TGopMtHkqfd6z8sU+NwhVLPE=,iv:OEJK/79uxLf/kngxDMjLRYU7h/fWucwYmuJXyMAAr08=,tag:UHxB/ZuB/KKVICsmMylZJg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:5s/AaCkVdbdNyZY8D1I8H9kRVAo5EwUDoBIe/Ynok4Z/KcN1Nd0n2ikBwUWy1yh6XhOtE4zFpqiJwzufIsPTyw==,iv:NHnxZXqT9xMml0YtGBx1S7aCOOrOOFwfr3J6HJ8e59U=,tag:u5Gt9Ercy2hBesxUOXeQIg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQk1BdEN4QlNidkNNL1Br
            bm1CQ1poYW42TzlScGNaeGx6UjJydUQ4Z1VNCmI1NnQ5My9MR2hiRXI5dE8vZWh0
            R0toSUhXVWVHMm5yY1RMd3h5K1UyRFUKLS0tIDRSckZPbi8xTkpiRi9jZTdTZGtu
            cVJBakRYRjY2b3BZQW5MZ0xjQWhWalEKeYu6Re4RTE9nsciLN1I84Q14W6gLa4CL
            CXea8b3TAXlqcpPsXrbuKBu6mb1Uq76Fq/rSdjneu2nfB7NpuwpLvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:45:54Z"
    mac: ENC[AES256_GCM,data:JSurdH/22LdFYbWvTrcMr5DX+RN23HhLMwlan9soFr/PHgiM6cuBpumuJQKO3xBOjKRFXtccuR+2ZOl1fuz62IsBMxkUkZLJ2a2MUJniHOLq6z9f5Zf93kYmf2T6jhivEX3TZRez9e60nx26QL7bAvCQK/LPaAZQ69wVPx5mshU=,iv:Lg+YCJNCa1AC9dla7bmxJbgKdYTTpSp3VhKfV/q+uTg=,tag:mPGxOr80A2wMe2X/ZMsRiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
