apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Q+AXIOo98yJuQdPymIOHjklLKqpkeGZn3WoBqyfR9BReq/aYz3u6Ko69f0g=,iv:RqXWmUd9mIuJI+wx5jDGVTy9HXSX62Dl7k7sHUBpT/E=,tag:kZSLBbCdSjKWpkVtGAfAKg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:UyxRUhn/LKVrlQFwVUMZvlhQQsqRMvCTsZuMYTkcmhWYDQ4kjm11fQsIF+7MIWZfohF5h80C5cnznf2oX1l8EQ==,iv:R0DjIV589Fo7kDZ05usJ+XmGQRy07+g3Q83BtTpza10=,tag:pab1lb7ziNkkUPzVvYx6YQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c0VBaDNSYUlraW04dWRv
            a3BkV0dTazVvWVFvOUhFcjFPcGNrWG5OWVFnCjZ0OGtMdDM5cXVHR21sSHM5SFpo
            SnJGZzNFMHVxZWxhZ3d2ejJ0SC9pMEUKLS0tIG8yV3RRMkpvRHphMmpXVUNUWHRS
            UUVwNlRuNDMwbWZZQ1ltaW5scnE0b0EKYOXYKbQJ14xSkofwIyyx25UxU7L7au17
            dViuGJfMJzh1Kly75mmKDWc0BIo6dgOqqE8OivKVtWt5SyJJf88Wdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:ZhqzDtie4SmjToEyAn2yyTYwFSrsobSUFgi5iQECosEFc5NiBayjNUIFnJdc76nmZf9F/J8dMeR/G3lKV13VOtKQHJxx51ZHZY9CZH9MuKd0YgBZco8o5aGKMsstcA/3W0vsEdFDBEHzvQ/PYt9xRSHj5/Md60ilRv2wBWtEr1I=,iv:fWCtZRCUfiW1G32t0WKNan9EoQ+uKIipNfZNoFycKeA=,tag:4gd5ImL0cIIP4oGOgj7oOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
