apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:1inJCjQxMPHbbcmrN/b7Jk87OSKmSzthVXT287qhwLRp5h/ya+zrjEfi+Ho=,iv:KwlNLkUeq1Yr41GC9G6BNC96MYeBaMNZfG1odRqxi0I=,tag:P6asVXhVQ45lV1Vb8eKYZg==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:A64wLPplO15I5SJy2bUK4RG/3gsOOLl7AJPMOXec/7Ztj8jxV4i/OFxMG25Fof3htB+OaUA0EtPBlALZ3ssayw==,iv:jRQuDio88n6eBvWNUvmOKFgeNXZuG+VUqvQvv0UPMzo=,tag:loLCwQxuKNfh9bQNWN1Tjw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZEw4VjgwNGNZN0o4d3Ru
            ZklKM2RXdmNBbjRJV09ZQm8yeUxjZW4rYXpzCmg0MHF2SnVxWjlpK1N5NDRDYzIx
            MW9ZRnBDdko3elZkKy9tWlhSbVRkSmcKLS0tICtCeG9BQm5jcUVnY3d1YlhkMDZM
            eGFCMzhRZm9MWHJ6ZWRhdUlMSDFFZzAKsV99NVmEAy3g4a2InyfIlzNhkMgqIGUc
            3jFp9ZIl+clG8yxeyynebtjvJ2bI/NHtD7ZT6vd/8N19+7dIoZcj1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T10:52:26Z"
    mac: ENC[AES256_GCM,data:gNZMxv4d0gDG+K5oWIGKarSibBpwtv200Ab9Wl+L5veoPtBZlGRvA1FKCL25M0+tIJW5Ze6bsfzz5v2IY7lPIlRRgArmbznIo1A3AtqLdkexFsqeWKo/SpJCu4LtNH355dGXpFunngnVkuTH0ixCC5ZxL5uz2+FQzOkrHuv+s0A=,iv:AZHrEPKH2JXC7GaDFlcvlSPqoapdXUqUHXkJ4W0e/w4=,tag:AEKrwtAIVlqXTym1GWlofg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
