apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: metallb-system
spec:
  addresses:
  - ${SECRET_METALLB_IP}-${SECRET_METALLB_IP}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - home-pool
  nodeSelectors:
  - matchLabels:
      hardware.home/tier: performance
