apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Lc2g0rcCPl8/K7L7d/l1ef5a3zf4ax7A2xEPTFuP0KVzGQ9cbJZTsg==,iv:LB5ER7Qxe9UtqZuw2fxY88/5dEpEpuTrnBWxveAJcmE=,tag:Pdff/x7VPxlyRTckGX5pKQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUU5mb3hjaG4vQXpWb2dS
            MnhGS0d4ME5VT25RTXArL2h5eGJTaDlldkdvClBGTWoraHBjRUxlRGhpWDgvbU1Z
            TDhGcmZjSDc2VzVkWXBra0lRL2dYRFkKLS0tIGtSc1Q1TlVtWU9zN2N1UHEyOTMw
            aTdmVHJvSUtBQjdzUE5nYWNETzA3UWsKCQGu85uoPnzIs66Il5dZagGJKYsQezZp
            3Y62JWuYZfPAceie158/qlc0CQA/834pHBawTzWVBf7Qfs85SqA6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:59:36Z"
    mac: ENC[AES256_GCM,data:OHjgrKDqTfb9BQe/APcN09XvqzJcCkiDqAL3oze3Su/42EgsktVQByRJ41j72LQgO510rxxo7KfzpxK2VrO/XhthN/vsvSdwFJPtYkdmem+zZ5/nYWkbFqsM4H0wsiWII/HWvQha8CYJ0brg6Q40bj9v5bDL5ZAFMF/JQiwe/mk=,iv:LYr+ADA/T07CFB337Sw7GzRsT7p5oZ17pCL8MS1+RuU=,tag:OL3tSIi1FFioNYU9DA9oAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
