apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:mTx8XwVJwPvczCOyDFvAw5VssKq9+8a/3PNeNrNmiDhm/TItuG7Yrw==,iv:hfwMcTK5r00LY3hVRTRU1A9WlVIPFxqFLTyYzhiS4ew=,tag:twZDUUnskarchvu1/dGDKQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UHJibUZPSTk2NDNKMGFV
            eVhYdGk5Zk4wSGJWR3MrM3VkNFFlM21Jc3lrCnN3a1d2Y090bVQ4ampFL2xyMWtt
            MzBISzVFVHVVb21LUHBhbDJvZG53TjgKLS0tIFA4bjMrSlhmeXJNakZ1TzF6M3U1
            aG9yeVF6aVVvTStDZHU0RWxDQjArOWMKywMW0IT84yy4tqFcXOG97esJgIE7kfdM
            t1toxGfMeyLfVGCvSzLfDmxaOlY/+hYMV8VSkUOpmyeIQpYf1B0bdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:01:28Z"
    mac: ENC[AES256_GCM,data:3JFIgaR6jVvpvn6+2fFw28ae8dFaOYoC22b3QXFxxyWJ6+X362dSkLWEhJus3Ii4j1izQYPKJzp7KcImQBsa1hKUEV7d1FaydQhbl5bbyazejSXIiFSt3vUL6ZLw3tz/E2ZzmWc0e0X2x9+WoCH4J/e/U80hkgXGrlo6nocPGDE=,iv:BDK8MjxwRP8ltmsKWy1o/Po0GNffzOV0BVHsDSGmsn0=,tag:HJ2QaWyiGF8zB6vlByapFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
