apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:70CL9L86FSOWNiHJfi3Cpn4hVUD3TLcgbOmkf1IEL2b5AqpSny6vdQ==,iv:b4ekmjak7xaAdBox0rFwFzOpU3q0R9+/a2HEVoIPzXk=,tag:Yx8xVQM87G80XgBwY2dz4Q==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a29VUVQ4QnBGdkhLOU02
            cE5ZOC9lUWZvYWNlRzlSa1RoRC83T1FpK0hBClNFZVVWK25lbUxCNmh0VXlaM205
            RkhvcVE1K2h6ckFxQ3ZFTUpOdkpFK3MKLS0tIGtDZmdJbGhCb25XYkh3dmtYak15
            di9Fd3hZQW1pbmZuRmk5c1pCaHJRRFEKKImFwMk4OqkREMnxu/vtLmqT27kGA/UI
            TagFBtIDWl5d8cn/PNcaXOkqlGety4zTbmfgFdSizkz1OjL94jfaUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:KBNUKV9w/tUfwmzmZEqdNSdj46UAnH2geD2XEBaHgxoikCUUcPEMTsjR33khEeegZVEBLW/QXXRKHXNZrMMxGzrypGVvSGkGlvrunCqP/IHQmEMVGcNN3QcsizarHlEh3b00NPQ2iA24Hme+qTeO9kxW2FmqsZfKlZ2YW+uRl78=,iv:X+OFAGmmGosy7/tIIcApUAJQ8+wKjhrMprYPPonKnHE=,tag:MeQyJdSA7nD5tL2qM1moUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
