apiVersion: v1
kind: Secret
metadata:
    name: netweave-secret
    namespace: netweave
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:b8ULTKUJ4jXWv+VJsFWMfh7vptxXTxpTKmm/VZ9MEc1ftiMxGK2Vryz7RvJjUJb9He3xqduxYlC03my9xv35IVHmOtJ062nMdpAmzGGyvh+4YXD/2n1bcDivFU1V2pBD25z1M+GH4rxs86VdDMH4mZN2twZcX2MenQHoA9QDoaJsa39VyGMWIHDefeW4RQ==,iv:3or1PRn6quaGiXRQv4cCbnGpk4NHOjHx3FtKJ6qrGYs=,tag:tAS3ZiXSGHAk/Ila5Xmerg==,type:str]
    DEFAULT_ADMIN_USER: ENC[AES256_GCM,data:hyhZVww=,iv:AbFKvh05cw1mE7x891tbkWoE0G76x/oUBEuOjv8OdzU=,tag:rD3g47wx5B9kD03nv5UQSA==,type:str]
    DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:HtTpsRU+G3SnqxpKbySO6xsc5GR8NQv/ojowmpcRSVUR8/1Yc0r235cCz/fLVChKHIhw044I5m9iIvQ3KVtPGA==,iv:1I3g2GPCVYzcJ+DjsHgD6YDz7vSMieKuOi1mHaYfvjA=,tag:zTwV5lkei7S1PmZuM9FzJw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:gxvR9YMOJfT/w4PMX9Ox7zWe0QF8FQb6ZWASsGAYo5Xw7a3ETK+U4KQV09qFYmaZBECFTe79C4cfmzrRIsVFgQ==,iv:3JN7zGiDA6JXAtXwQI7QqEpAupmWe+kxXykfZVl1o9U=,tag:piNIg1XZCeZ2idVPLUEd+g==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:eLmYRpsgPtV7+cI0sgIzd9oWqgHoRGNjvI9nsPz42Yb4oPjABdhwo8/MdY2l0nmFBC2qolQaia9+vkZhVctzdg==,iv:sUcDjAgLuI7CcTxNTvHdxydQlDmP8VGrZojLm7Xobhk=,tag:vSf4jK88LyeH6j5iMgbsDA==,type:str]
    SESSION_SECURE_COOKIE: ENC[AES256_GCM,data:POXgAA==,iv:H5jrzzcSc6eUWniW7O7wDur0EQ/6JB+y8+HQ3qf8ri8=,tag:DNL8Xrv9wcMmqRSMKBuBzg==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:kJPEulBn170CXVQ4QictYYvMKsHU/WiNeTgxn2/1S4f+89yY0sxwXicNDC4lCCrERp29qZYcgGfJPG7qVQRHfs8ClyJMMPmD1xtRfA==,iv:qWz71ixryPMD/AzkoOPJCGP1EHp6EabfJxbb/oTwUws=,tag:wSoMb5izvLX3ravpyfjQ1Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:jKzVE05yweK9VF8eWmvHthBLHE/T4emGI5sa6cE1Y8b/8Ppste09Aw==,iv:jcddMIoQdzbTvi1Bmho3Ho0zAgRbeb9jV7QC/Bcy0vo=,tag:ZidXuWoYIIvsc5UxmHzC6g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:2kTmX8/oR7m6vUIgN8eFJw7KMas/5Kv+lyPfsoN9HLiq81vmcX+7LHWeyKpHKL+SOr05ZOf0y9i3xYjtLzr8Vtamf+laidhIWk93RLqa8kryCKJKyTDlxQZ3HD26RYyjSs7NkJUK4KRQ2BrEmPRMca7o/cgTkIG1dhKwYFLpvj0=,iv:DvrRG5ZxG9dIazb5HC0oC0tQITvdoNsd1XE+3y0EctI=,tag:UgrHTQEb2NIy50QcD3Y2KQ==,type:str]
    OIDC_REDIRECT_URL: ENC[AES256_GCM,data:/nIYwzb5JPpCU4dllWKkG0gm1Bwelndv94hD//0=,iv:HmkJZerqfWDuUr046TgGXmeZd7VB1l93SWUD0jfzRig=,tag:6FJY4x1c6duzVdwO7Cml+A==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbVJtV1hUOTUvbDZhWHlO
            elNTMXl0blBTNU1ZNkxKd2RYMURWc0Q2Ylg4CmdYbmFDV0RianhHOUVEaHZaazFv
            aHh5Vk5mTXpKVEVUNkF0emlZMGl0ckkKLS0tIHlwc25BcHJTUlF4dDIyQWtqMy9E
            dkE4bUFqZmhrR1A4cjVwNjZsK1IzcmcKUbliizqnbW/4AAgWKYwd3I04GvgIyBNA
            UTDVnVBQxP+/hpm1DhKKieyub9jYF25BwsWtGgFFJCznggrikqZbrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:01:28Z"
    mac: ENC[AES256_GCM,data:ldVM0Y1I8MSKT8gUdiOFn3dBbl+LdllgsUWVAoYDpGxqZcQmy/0Lv7c394kEHUXqjAY7xwQykAmWMKK4NNXw1F2YstoiYis4O2RM7nNTsmvkLjjDOxdebGfApmJQIk3jF51etd4WDgk0Si70HUWZHPrIKqUBWPtwtddoNd0s0Gw=,iv:C2P7L5ZAgFvT5p5u044WvK1F4eyiDaa0k43yWeGWUvA=,tag:U0r+hwQp87oA1/q0LYYkyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
