apiVersion: v1
kind: Secret
metadata:
    name: netweave-secret
    namespace: netweave
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:n07ZYE+Fa2CxuuZyQHT5qVv/l0qb0NtqCsne58j8ByU1QbVaV66hz60w1Tg9GK+6Da8Lo0XvHVG3fLZ0pL6wITEyEb1Kfd7Y8UFyG6H0Y44DMeEp5qG53tWaBWqBBk/XcdonqHsDzOLRe4rKy9e/yJ9qqmYerGzyWxTXTo9NylwTeUIFnh4xk3gyu1MWlQ==,iv:BJVYTg0erRP4frch6YNncRJEjRlkaxpTBb2RXfcH/A0=,tag:6Z7fJPdviwYC4lWyR26ZPg==,type:str]
    DEFAULT_ADMIN_USER: ENC[AES256_GCM,data:8/U1Vm0=,iv:STiws0WZ1ttru/7yVkJMBhDbTLZAwVoMEXCqfheTZ+Y=,tag:iwjb480hJ9RLErcRN/mK4w==,type:str]
    DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:VI45XN/+NKSPRXKSpRswzxNWyqzgFHuNAhb4UNSIBoac1JrknTBFEmY2c3Ffj7Csh+rpiozPQxIsp05D2ea7VQ==,iv:BslGHne5uWx8e35ow9GipVVJAYXTOlqX+BBgbHfhK8g=,tag:1Q88+sZXwspnQ/90VNILVQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:GYv/K38q7dji1lhbZ2/WaIkj0PiqVpnB/ivQRQ/R6JVb4BAKqR7Uw9iCsiuJrrS4bXMFlv1+cmNLSbEcG88mTQ==,iv:P9dldwr1dMMZHCt7VYVDZDBEZJV9VUESzQC4MALK8Jg=,tag:vLtcqCnG4mqBCOVYskoZZA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:pTqG1gU2ZulwplWPZoM5fUCIxCeoyim1sPH6fehpF9dr7ku07erMHlEIAOtQNqoUuhFbySNI/Tc6MGheU4fUDA==,iv:8JCtv84lRsedVcpT2wn1pAizFR8v0G8GIgIwfJlBLpA=,tag:V2l2HtQj+bEdMpQC2z8FAQ==,type:str]
    SESSION_SECURE_COOKIE: ENC[AES256_GCM,data:ZbeQkA==,iv:Q/G9UWMadMLXjceyqtEnfgjSyp9qYf0xD8hbgsHn1WE=,tag:fTX7r5PjeMyEbeVFWr1nWQ==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:jMSqjo7gOogfW+lM1FcEVkLFImielb5/QnfjFnpyrLL6D5n8vyRROMn87T6TwkGCYX+zyrF3zHw7DdRdbO/hLdAizihKRJv7QhWj5g==,iv:exppVp/MqKmxq1Q0ZD0iRabbfiqiPkvGCMlkrM8/ZuM=,tag:GSYYn/2/mYBfLMtXMlvOYg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:tG7Eqcpib05k5hlkM/OayKZlaUBhcUGVCi1QYngeOywbnF8Co8iypg==,iv:4UXHt60I8fNLPdxFnjnyGjRHOM8ywPQGHsmVMRWBuo0=,tag:DyaMnw4TOAilYhvBoAHRsw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:XzkJe7X9NOUZlwTL183ntZlvSoucsyC3gtk0EA4pKf9wRAThQeSZ5Adnl+tUb9oSob+EKQ/mfZd6jVvwVn6UK0cit/3TAfyGqoYDf8XxpPklNpAYhSi1xXrNRm8iZccOui6kxUkwM4Vdzg4vFQ1VDJ7K7s9DT5D25XyQKnJ1qyo=,iv:Glr2DfBDs213O/UBReK3wLf5yzjo3M2YmgtJ2HL0S8k=,tag:eOJ1TnX8dB8dnKhVyH5UAQ==,type:str]
    OIDC_REDIRECT_URL: ENC[AES256_GCM,data:mpKRUzAazzgtReLFd8sr4TWKESxtEAj9Plj4so8=,iv:z3NxPI5asv7MWTvAyh0+6I78/F2awhcIubvqPb84iHo=,tag:+TtMOKHnFgFusRcymw5oHg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTHlKdjh5aUxGZXRrSGQz
            aExhcnMyTzVkQzRlQktsVk9OUDdERkV2bGxFCmpYL29LMzh0cXAxWnJ1eWRUaHhv
            SGJqMTdZWmE3VXdTVlYvSFJuN0hoNzQKLS0tIEJnWGxyTXZpMHFIRjBwUXFPaCth
            WG5XMnZoVm9LWTFhTEtXR0xERjI2Q1EKD69P0FcP0f+2rZJSZW4gapNWmTvxIPpg
            tQndv9NmFEh7jtav3P9RvFJSnBEYWoX6O0r1TCHdfo9XuxBTgh9Few==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:9qJ33V/J3CnI45HOMWmv32LsDMCuEMN9BNfvqo9iCfVLbEFtt7R89n/XV9ElPlA2OZBL4DEsei/3gjg1SkLnExze47FD9myS9rTuLEocACnTV1yotQ15H6umkWQhMqgm3ljjNH8hY5m/1eQoeykt3mGuSas8GFOv9AWqUSiJBrQ=,iv:uaqKR8hPgauLGp/VeSqgZphgBOCeNamHX8KZ714QLwQ=,tag:OTnQgXjsZY6/jdxYXwi9EQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
