apiVersion: v1
kind: Secret
metadata:
    name: netweave-secret
    namespace: netweave
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:gKO3TlHjrsiNI9LGWWntlrP7gjXMcibyGpwb3KYS26aoxm9vUVZ1S/e9/A/m7mTjsc2psGSCEo9YiJaj73QkLYdUywrox2419NSt2UNss/uWss+kgPv3dfhdvCHhZbmPR3HU4OZyEldoW41tIulp6b8NKkgpBxsMLcNdL8XvH4neh7TAg88yrPNxLhQG+A==,iv:4lxW9Q5G6sxvTbTKgMnex2fZMSIH/bJ/tSbsUZhKCnc=,tag:xDaRMB59WBocMh0CNHYY+A==,type:str]
    DEFAULT_ADMIN_USER: ENC[AES256_GCM,data:bGK7+I0=,iv:gMqHuT3/K/iXW42ja8Zym3PRJTt9QahQNRIzsDBh3eQ=,tag:rjwxapAwTpRFBChDbEogqA==,type:str]
    DEFAULT_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ge3cat2QUa5iSzIbx2t5KdKWEvlAq39f2lHYqMfgGJ4JvSaBjbhXOarDAMsUoJ2Q/4ONlYYIJZAt27h42DzSTg==,iv:5DlID3EhglJeUgr6FM0TtPWR7vFwqiPqp9nvhMRl8PE=,tag:zgNAkCmd0G3hCYy6ftqRSg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:6joV9nu6jYR7qYvwcz5srIm9IG67tF8kP1gbe7TEhPoT8uyQ9p+VXDGIAkDM0Ikz5PuaI2vm455XFitcEt0jrg==,iv:JWIcyIsc9jvadQ9X9sxOGGIKdP83gf3u/wvLiBW8u1w=,tag:Gc5ZEEf1Uk04CVzN2ftTlw==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:pk6115WIc0X6hGQNtM9vdrQaBBgjfKbeSW4QNPD+3INW0ngNGrBhV+tkUOHrUN3rT5CvMBL95PhzYuz9i/ySeA==,iv:D6jvErJ3RL2sudg14cGrwUeVLL1F1dRn+scsP2HoErQ=,tag:jRxGVaKMTcZgFGz+AIlaRg==,type:str]
    SESSION_SECURE_COOKIE: ENC[AES256_GCM,data:Hu8eYQ==,iv:teTagxCcTUXjhaPodjOhCKf2SKI+sX2aRxPdCcW699Q=,tag:dkG/w0ZbBPzJGLMeKKtkuA==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:Klp0D9DatL8FKV2RroN7KjSvVgkQMOFedo7UiAWXGcNCoxqBmENio9zJKNghk0K+hNFguK4lDuZEPg9vnx7TH9MgCWG6XiX865aEEw==,iv:7XFKU2YLMMfwxj8mdi/UvFB87nne9DfhzWq5tUOGJAQ=,tag:Tu9zYRqc40wyXborYSkX+A==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:QeYLQF2EGEDltDOhWJJDJNNnkJIrkebj6fAGmg771QyExNomy2E33g==,iv:yQMbpFVTAvRSMm0MY8BS4EgYzRP2/32HzwePzhR8lJM=,tag:eZrsrRotWu0FTNs4swfeGg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:jLRHhSfl42EH9qnY2154yl6TDUgH699s1wT4KbDa+acc4CB+XSV9MRrN0D26c/LhalqLsF+9MJIv8fuMTotX8V/1ewBDmBscJH9og/RVTyYFDuhOOiW7lv7FkQT8vxg8Yi65fmj4fsxuIdFx6o8rmAIqzvvKG+wy/06vnpPhOUA=,iv:f3Ac6LF4/7KHVBv5zoRf02Wy24nOB9HwPPdZaRwh0ms=,tag:IrCUlBGHPboYYG8l9FkM/Q==,type:str]
    OIDC_REDIRECT_URL: ENC[AES256_GCM,data:lkSsXKaD9yEd2MUI4fCzHNL4FqF5Aa4D1aU1nA==,iv:0BAF47j/FgxAniqO4zNOcvAE+ixHqUmv9nt9Go7aewU=,tag:sTm5i1Hqq/7vP0rQYqLbHQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZm55RXZKNEFsVTh4SVpP
            NHNidVE3SFlaVGMwb2dQeXNWSGhnRFpnNHhrCnNLSStLUVRiM0ZXanl1dDRiYXJm
            azRhQ1htR0ZrZ3VpdHhRcm9rNE1qTmsKLS0tIDVHZ1V4Z21EOVVsQVNLTlhjc3VW
            bEsyRXZjS0R2NjhnYjIzdmh6M2xTMk0KsEd5ZEL3YYgEjKtPqI4Ep2UL1HyyW435
            RYFfFkOdBVNfz/+TvovtY/GOiGcLJt1UMW2hXVUSSnWuBsTvwglU+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:59:36Z"
    mac: ENC[AES256_GCM,data:OnsYieOnEB3Z2tprRqzjubEaocdhbPKwigjjWpbswkKJua1hfsLj2vNOQoUy2xaebzBfluOdUp2Pthw4bwO/xkCIOe6AoIunzB6Y6J+do0VFTkYr4PyNs4AqBi4C5/ggkYkHRKJk15mcALyJ/UoeWZe46dWNv19Svu4knYKA2mg=,iv:w0FuhjMJGi+iJLL7AP5mWtkenRFfmUUWnq+saH4mJzE=,tag:79Du+Hfqxhs0+XqSwCu0fQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
