apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:Ym8daQ6+rOjlXfzUq63wBzrVmWStfgpLiidPLUzLGDVMT7Y42hSjuEvLKiY=,iv:4U9UixVbOky9ZfHdfoRfH378sE/afEMTxT4yUNlZIxE=,tag:MODjLHzEjTgR9Lng32c/Zw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTDlDYmVseDFGTzBuMFpp
            bzFyakZOZEF1eEV0TmhoM2RsQzhSaDVSSHdZCnFhTndSOW5OeXVRNGNEZ0JoQjND
            MjZEdXNRYW1SMWlibWJkN3dtejdIOUUKLS0tIGQ3bm5qbFkzTVZSUnFGSnFpT2t3
            a0QvWG80dk5hL1FEV1gvVExnR3dtZDQKR78Vvp9g/Ymi/alrl6thj+JvLa6PDKET
            wxY5XI5C6FKR7RYMdHwmjR3Vhba25p3PTg0vAFWizwZiFQEtMFTeDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:GNXllyjgSu/SOJRrtq9jiO4taQoqXScoIroibaq3/Zq40kV81VrGACyzNN95wGKjTuWklsxGXqdSDhdSREIXk4Y0DyGiILXIb5i4TUlj/kyN/biqORKv0LW/sl7VA5rkxjG99QdAJRpg/d8pwTFrrWEVl94meUC9IhS9xx6oe34=,iv:rr82F1MlOpzJ58is3pg5FfpYYqQf+7ui3+IsdRaIa7I=,tag:b4M2uz5cdgOmfZ2q6CJm+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
