apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:dFuzTuWl1dEn5C7n41cSmbBWHO7qKoiXdmGd8X5zl1OHWYha5RjHeFNo9aY=,iv:TAC1tRFGkis507YRAHHV2zSpoDS6+3bYdxHGkhUQCfQ=,tag:+U7xAtXgS3Vv+Qam6hHkew==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV3JuRjNSclJUVmJXTVhN
            aWUzOWY4TXRJeDY1NkJSMk10aE42bFFibVNzCkc3ckFkcEZDQXMyL3dCRDBZZWdV
            RWtxalpzMXdtb2k4RXNmYmJrOGlJMFEKLS0tIFhyVlVjejJrOEc0U09YdGFoTnhU
            c1hCZW9mUXJnVS94QTAwdXdic0hiUVEKR23nEhYxcScMoh1Gi1c1Y1uY2KysdivV
            RIDwoJeF7p0+x5CRErfN+38p6IlmSu4qLQP05c0/Az3a9GMgm5OsJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:45:54Z"
    mac: ENC[AES256_GCM,data:5d6tzyoLwDyEKjQvApvtkq1sQs0OCYchKEr2LJCTkY/oiM4H3m7YMg4lLR8TaU8UqVqaJ1Ajehg/t5K51xF1vUn2qylqghetV0pkRePmH1od4BnBG8r/swQdciVH5dV7gg827a4ETp4a8ZOJEJ4ePhZecrYue+oPM8H+ia6D4TE=,iv:rqCG7ecoiiIjSECU8Qrr213ZjqmZVAmeHHQiXbuO+Uw=,tag:HJaNFWjTwIzZn/uULHf8Sg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
