apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:UMNnQWg4wiDbF+f5EXQ6E5XvFBuhc2rfOo0wSCneE+bwXr4ZXhc2CUvU6kw=,iv:SOu9mAu5PFY8+MvGsZfhAg6GlwkWoyu+jkK39DaNyS0=,tag:NwT//KRePtOjIGAhzuYPSA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOGNjbTNYK1VqUWdMOFJB
            MmIwZFlxNlJtdzZOZ3ppNHZYc09DUGNwdjNZCi9MMnJFWGRsMHJUTXorYU9CcGlm
            U1U1dmY2RnNOOTdxVlI3VWo3bkZ2U2MKLS0tIERsOFdRcDRNVDNvdHp3aEI1Rm43
            ZXJGeGVsM0tueHh0d2JhN0JmeUhmbTgKlqFWBjwnhYk98qXNlbl77Y3F+vAB3m/N
            vNi6f41MvYaEgfgw6N189q52kpGG85/J0m815ee9mpbpIE/EIQ46sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:Xy70IWcTYnzBQyUOHv9//hymbQpt4JtWMz9unwisQtMgxlBBfX7JxAA0FDp3qy37QFYAL55A+oj5sLn71p7eGLl94jpSVqhXUJN1HeDfg/ciQyGlnM+0VmXywCOjoaSsAWL4ZEE9wUsOWE5KXbXVkjylJUvTfSl7rxzfWuY0QG8=,iv:7bsYoqMHnybN6yPkSPk0/0TvwzmKSpyC9H1f88XgZ4s=,tag:IkThlG15ZwpJwL6jsRj3PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
