apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:EPIt70g/6QHukYYMg5vFRcPz0HY61reflg5FNeJZECzMImqukNKaZ6WCAm4=,iv:EYLDDPJxaQcKAr4yhhMdAVjEdPrOvWdKVUOBBQoKzDo=,tag:FfFvls83Nwd8KZBiIaEL1A==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdWgrL25uNXo5cXBBdGk4
            TGNlTUR1SXlXSGp6R1V2d3JTbnZJRHNzN3dFCmlocUNMbko3V0JOZzhLREJJaWp5
            SThWYjZaY055eDBqa0h6aHR0dkxpa00KLS0tIGd6UXZVc2dGNXJPSmE0N1VzN2lm
            M29zVG1GSzFYcVR6dm1DWlB0WUdoQlEK1eBP5/RbGFarKZhbP4GAxOtukiqLAqtE
            XFuuy+xwlcQVr6GUq++pduiciY6Y0PUs9MPPOMW9qJKcJvi7esWpaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T22:01:28Z"
    mac: ENC[AES256_GCM,data:5ncxVIR1s/fd4LknDUrn1Lq5joCH47pY1owhKVvom4Ru0bAUWqlIn8MoyADD/kUgTd88P1pa+NmjlzT4lAmnaL7LFcgH6bJknxM1NG16EGHgROyxO46QHxCOs6K3MXUFnx+b9DWbQdcMnBlk6fAgdYjfezivCEJxMrehm8/U/rU=,iv:EFTALzs5NM0HUFp1XZPx8YTJKJfX1zwNy6SUKEOYr00=,tag:WOh002mEz2JnGZIVvBCupQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
