apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:Yc4EClaSXxovfdz39uVkm7UBMoCkr2Ta3aOQqUzC9z/ETxzKri+qBB6yjhQ=,iv:dlF6KlRN9/IaRxlMxxS+6DVhG8mBirMy9ij29+wjftE=,tag:gxySCM3Be+DOIviPnmidqg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcFNOcjZQcFE0bDJ1dUVE
            UXByOEJya3J6SjVKbWlmMmxXOGVSeXlCS0UwCkNOZHdjZ0xmUmU1ZXNzdDg3Qmcz
            elZpYVJvcURWSE4rQ25YWlhDMU5lNXcKLS0tIFJOOU5CQkdGVmFCazlBOXdUQlM3
            aXkrVmRSeTJLTW1PdmhRcE1vRUJHZFkKkk6cxtb4oQIRZb1oNdLD896GzA6USUaQ
            kI7F+X4Jg+Gssxe/tEWcUd0rX3Kovco1iLnnlOrX8T8+++iALnPpkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:59:36Z"
    mac: ENC[AES256_GCM,data:cfGwq3HGrFL0HHyebE+dl/EUbpHlCKoViaeVMXjlO+XWObimMqpUgRcTQXib3fXVfmEJSxJtYTYo1bRlN5GDDJwG8P7175Yq9Kbcu747/ur/qLSJomYoDMvDNfEzHstjVMFFi+KFY+C2sn/4+iNLer/WaA0OVkKTMHm+RcD5Qok=,iv:H7GJts7PXPtmhPo6m8QnrJvqk2Gce07+kNfy80WUgYE=,tag:FEK8azTMfDgSPOSRp16F/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
