apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:L3+hztARZB/dcHdgUB/wNNYF3qwJ/UPKJMg/QwjyzlNmUJxk+WbuvXXSOVk=,iv:4C3tPlmsjc6lKhMa2H4wsVMVNBFa/ymT3GqHECij2sY=,tag:X1lL/XbOMeGyEJf4G2tIQg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObjJ5NXpOR0JJT2p6Mjlk
            WDhhdlRldk1CSEEveHNmTEV5MDdTb0dONGw0CmhpcDlwS24wZjlrQURTaGRBYWZV
            aXBBSG5vWXhaODZKSEpPWk44eXhZaE0KLS0tIFdOVGxuc3YrbytDVnhGKzJpdURT
            SVFZc2JITjZ3UFRhYmtCeWJIV0FLODQKTEbxz9xdkw+nvYcEnl2E3xhiWRfnDyRg
            zhIdu76UaWRK1R7oRY/fbIztT43TEILTfBcWsiA9QzSG017OsZchqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:8SzEwN8tMga0imaRLsPP3KB4MRtfyfu6jSA9NKyghbQvfW9LGetdhR/XwjP3O0U8+etnBNtQ7FgfLPGeeHcjpeHXk1KUAb2cDinWdPpB41Cyeag0hc5h/tkH7f455GetUzE4WhH3Xgpa1ptGE5AA0kx6DlLwjD6yENAHDDJy/8g=,iv:hXmvBAv8eAXEwYgcdKyY0aOe1SqlPJ5x54LBpzpE8Wk=,tag:p85vfgeXJba0QaWJJb38DA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
