apiVersion: v1
kind: Secret
metadata:
    name: netweave-db-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kVSh2tlZegQ=,iv:arKZ5SjFBeF/CAofqKVuB6PULbXBaG20l9hiY4QDQNc=,tag:cugmQulGqpUjOsY6bqUwRQ==,type:str]
    password: ENC[AES256_GCM,data:2TlutiCEqz+d17w2HJBFj0YxJc/9eCu3PVpsrUR1OrNpyFLzxrgLxcl4xODyuW4FzYnQZSt510cL+qDFdHLaXg==,iv:gyFHGzG9sko0p3WLl/7t9pcB6f9cwFjOK4i3NXiW784=,tag:BFT5pwI/UAaBjx+iE6KxWg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaEx5UXNoMWxUSkJpRjAy
            dFpRM25hOWxobUlpaitCY0NhaUNjZGhmR0hnCmdTUml0cXRyZUJWeU8yRHFWVDg1
            NDhwSkRsSklZWUlZelpMMEFCTVk2aVEKLS0tIEN0dml4R2xWRFF6WnNUaGpVRlJp
            SXBtREZTdEpScksvbWNvVnZWZGZkUUkKwJoCbW3rYgJR6d4Qmsm0TKuo2k0t3KW8
            utBRR+iLlYukSj+9gaWUg7KBhvBL19G2h1DrjyAL/gQfWVDSxaQ1Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:kIJ5iggCdMhiDsRoUtYhjHZ4OCefB5Ptu1iKXxT0wsdFAbCelXrkKtDiN3hsKZ2I0XR6jOHjZhXNVk53NtuYIr+FDa6TABFbjnhzN1hh30d70oSl+O1b3Dyyqe1X3keEbQx3+dz1Iku2w1KevLpr09+idHc568rKA2JlZrDEywI=,iv:BdyvLUKbUoOvAGakVOONZDfoedqpEUaUeaxGEVUZpX0=,tag:XkTqFGdMkRXNxHHeGvmTHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
