apiVersion: v1
kind: Secret
metadata:
    name: netweave-db-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LBd/8HWpnu4=,iv:wO0VkveJk4Hm2WeMHPhKBiHuWInJR26OvNvgTwLqTHI=,tag:IJ3Uv5o/YyB3SdNZoDrd5A==,type:str]
    password: ENC[AES256_GCM,data:oS9mv+xQ/foIKeiM+3IjwxtEWI9tkljer3YPbn4sAVN5Q/qjtKnX6O8mow/DJBRL1PAgwlLfg9ZdK+E3zheFiw==,iv:+4RKKGy1AB57fDy8NBzq+uGV8+Gyw45u6O2DGbR6apk=,tag:nzVBwEY2NiNkPaVBB9fjkQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bjRROE85SkNxekd6N0xh
            ZlMwVSswSjA2ak9CWTZvQnNuazRkSjNLWXhjCkxnVmpSQW85Y0hqditmZFNKdWxB
            VjJiVzJ0YTNYeDdYV3lVem9HUSs0djAKLS0tIEpMcmh2eXQ3QlEzblNLZkUxVjNZ
            cW5uVit2VmExRXJjN0FKU3hoVkFUZjAKsJjJYXIQ4JnHQTDgfmgJlE2CrXi+/rEy
            WRQTm/Fa51kHnbudtrVT7VZiK0LTt4UhtrqQPU30x7OQmsS8VkDq9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:kwQV/ln4FZZR41YIM0XpAggEo+HK7DGnJyUoPgLcSSdteVJ9LhyxEn3iIgsBd7mxPKITawLHsbPk2KLYedDCRp2oSkjecslRmD5LgEj5Gb+oJc/Rvk53EW10fqV9gYO78zy4B7CwfAYqDLQ4bDfqDGFzdolowejGcr34SNIs/YI=,iv:SF2xvCpe+Fcl6nQ4Eg9S7Oj1A5sUa6BSvk6oOW4PuJg=,tag:zSrpWNBmDXC8kn4Q+qxeQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
