apiVersion: v1
kind: Secret
metadata:
    name: netweave-db-secret
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vAM95WN7nrw=,iv:GQ/fIRMP76GbZ0RX9kqkqlq0O8b0qmak/br91STX4Wo=,tag:ZPv5/aHKRq7zfvmbANI/rQ==,type:str]
    password: ENC[AES256_GCM,data:JkkBTptub1fJD3BBom82jFHmkHXADsdZGkZMG45pGrfCg5+VlFhR3jTXChQcLgJTE1uc4sy+xlP8IgHIf/zW5Q==,iv:EyHjLEyQdF9I1p0/sV50EuL2MNCgpn+h32pnyqoTSt4=,tag:rXKYy+c165IIBAwBXI61vA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeEcvNjFKWXJ5NVlqUVcw
            aU8vMENDaE9GWVRKS3EvdnF0T1RIU1N1WlYwCnRzdkNaZXM0UW10T29acEVVNUJv
            MVNZSTVvVkFKYWwzQUZJcXUvb3lsSkkKLS0tIGo0ZUlGM2VtRC82VGNZaVlQbCtX
            NzdKMTZjcUwxNEdUWmN5ekVlUzc5anMK0jAc26NkEa5bJYxjhSf/RjpmQu2S6LQt
            wiPrcZIokQSqs0JxwUh4nHQF3vjpg7nTUhe3r9ahNiOqqqQ9VSJhng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T10:52:26Z"
    mac: ENC[AES256_GCM,data:quOoBu9WnaJwNlsWtmArM1tL0wZX8entPl+u4dWvJcqCUJmCky8ge6IqDjib1PJfo4g1lv6v8s1Ym7km+yt4dtSevH7YyMw/wCthurUEZV3viibIEMKIwqereKJgCEtgHcT1AkU0HndtvsNDtDJSTdIDvTNhFT11WwBDNw5Ai9k=,iv:uoTYkJVEL15Qr10zde5YVvX9AuDE7eUAOjil4Nei2/Y=,tag:C001To2NGV9xxwVj5Yhs7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
