apiVersion: v1
kind: Secret
metadata:
    name: postgres-main-superuser
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:+xst+EEAR/ZNMss43okP7QNWujDm2bWKCBKDzgBCa68=,iv:4vsBYLmnOCuYhCD1BHYyJrXKCV++l+uYArRA/k4MXjU=,tag:rhyW8RNBo4MnrU2saFJXvQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVENQelBwUjU2bm00TzF0
            VUVhalFwV0FJY0hXUmRqL0tBWnVwTFlqakRvCmlneUJGK1Juc2RHUkd4YlNQbU1z
            S0xGVnN4aUhXd0hBNmJTQi9qRjNBWFEKLS0tIHpFT1ZCRFdZU2pzb1dKRlBIc2FC
            ZEplS0hYUHdnZWtsNVVwM0NHampiWHMKvr5ppF/K0g0D4TrK8Atz6+gksCkju+Pk
            HrNsj0Qz+SNzrwjNWdtCiaVpe6uqTqgC3UaBdhMjxjJg/HMi6uf/Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:Vva7P+Nb19+nx7ZCAgPlZMASZ0PYcwK5B8ayXjuF753d7OtFboQ1cmqC2n+RI/xoRvQR1+mzIrnJgejWmkfYJTqFJwhsWDlSbM2DTBrtj4eWVlyJtt3ULHEEUvxzzDL+ndTxkc8bE6Sgeh7V+o4fhFtciYTLG/yrG7PF1FcDwy4=,iv:yNMVvbsHW+GGc/UU+spfwd38lSZMBIe17DRap7aRHe8=,tag:gU5X6v/59iZQkEdTllqmDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
