apiVersion: v1
kind: Secret
metadata:
    name: postgres-main-superuser
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:h61St7E3kF62ffcaZwNyP7lcgmazbBDcJ/Gx0iLbiMI=,iv:fh26NfaDXqqpZwV6vDESO7ZDxtf01x6MlSAcSXP8v0E=,tag:Nmh+N72EaVXiGtYP1c4rEA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUjFvRG96Nm05UVg1Wk1V
            aFpxaEtCWHVvWW1PSzU3RXZSTlV5RllMOW0wCnVLbXA1L1EwZmhqYm8zUGg5ZVRa
            c09Xd0M1bXNCMlI4cXZ6YWVjLzNHZncKLS0tIDVOaUpqVkpsQW1MN2s4ZnJIRUJY
            cjZWU0tpZmNVa3lEbmNRTytKNW16RXcKVvu/RXv/2QSE1BbrPzM3XJTEJ30JvYt+
            IemL1uY9psPbeWh1f6kMhBqjuzvSYxz7yLBJ/BMofn8Yty1ZnSUldQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T10:52:26Z"
    mac: ENC[AES256_GCM,data:5LCKy4tFZkgMMYo0q2uKkUa3ISpVeQkuSrJXeHx4K3dNZPr//jJVr819tHbqtSqpfYYTCnFMLSBrgtlfE9gHKQdJmxWEn+PGiHzDERHAKAaqH0BotjinwfP4GWLNkc1R5sOAPQJtym5OdtgnARbyWWJ//xOkpCuxgHBNHJ/ywos=,iv:sYn5iMfwdSTas6Ex6/2QtOwtsYschtOgmpyZ8YKehak=,tag:bwDn+ru0eykvHbKkSXWTtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
