apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOGxNZ2xxNW8rSU9XcGhq
            dFpxdUJaK3N2OTR4ekJvRm8rdUlDd2lXbFhNCkx5bzJHeXlDeXJDek1zblB2Z0pk
            U1lCaFluME0yQ1NSOEQ2MjdZQ3Zqd3MKLS0tIHpvemZtQ3FpdS9VVWZ2R2NSWS8w
            eThsYlYwdVJkVlluT2xpeGJkM2RhcE0K1pg0B7KVYRyuLLDAC83vZByeYOYEK/+H
            +D+nGucnNW4E4IyAslxpl6zY7/rMik2DlsUOGMSvAvRIc4Lv3Bd3hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T10:52:26Z"
    mac: ENC[AES256_GCM,data:EDyhL7rzLoWBXBeY7iyjtZHSacCZP5s8xOc26UcEHBWQNlfCc7gSVDysLqtVLerr2tO/vh9ZOG5+9SFYKPGQgvfywE2iZqGLqKjPJcAeQqFeZEIkR+tkqpwJaEnzpX+ZRr4YVIuAq2/kmF2ZcrZaRcJ2yN3EimNbV3oUQ4yC+yU=,iv:rNxyoTsKF1CcHIljtG5DEfGNi+KErd4u+5WEqj08uiI=,tag:IVSkweUNSj3DPeKeXdw/jQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:QCkgh9mD5Rt1leyjnMoTsDjo/Uk2C/PX2syYRn5DgG0Pf663OJKAdKxFC8J72l9Ve3xLBSJglAinqhAg+2+Bg655JJoIZ6GioSi33ZyTTXP0SGqAmQ8tbRpIdMIMewAdXshlC805exiqCZLFA3/nCRRTXzinjCF0Kp6cd/EdVcrhy3WTRqAWxmO+x6rTFg+/MVc3YFyCGFqrk0F6YgPq0+cJPCP4aw5ytPrs4G9r6tFnpRv6789AKA==,iv:TX014D38plHP3Nk4aVEP07wWtRW8PENRENsuqP9iSbA=,tag:peZrEACLJgEuIaCxxHqzhQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOGxNZ2xxNW8rSU9XcGhq
            dFpxdUJaK3N2OTR4ekJvRm8rdUlDd2lXbFhNCkx5bzJHeXlDeXJDek1zblB2Z0pk
            U1lCaFluME0yQ1NSOEQ2MjdZQ3Zqd3MKLS0tIHpvemZtQ3FpdS9VVWZ2R2NSWS8w
            eThsYlYwdVJkVlluT2xpeGJkM2RhcE0K1pg0B7KVYRyuLLDAC83vZByeYOYEK/+H
            +D+nGucnNW4E4IyAslxpl6zY7/rMik2DlsUOGMSvAvRIc4Lv3Bd3hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T10:52:26Z"
    mac: ENC[AES256_GCM,data:EDyhL7rzLoWBXBeY7iyjtZHSacCZP5s8xOc26UcEHBWQNlfCc7gSVDysLqtVLerr2tO/vh9ZOG5+9SFYKPGQgvfywE2iZqGLqKjPJcAeQqFeZEIkR+tkqpwJaEnzpX+ZRr4YVIuAq2/kmF2ZcrZaRcJ2yN3EimNbV3oUQ4yC+yU=,iv:rNxyoTsKF1CcHIljtG5DEfGNi+KErd4u+5WEqj08uiI=,tag:IVSkweUNSj3DPeKeXdw/jQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
