apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VElUc0tYeFhPV1JHZTYw
            Z3VZZjJhWFdjYUxkUFEwOVpXQXZqZTlac0N3CkVLYVhyc0taamNwbzIvaDVJUFRO
            SDVuN0JWV0MzbUQxOThvZHJuSHRJbEkKLS0tIHFRR2kxM2JCb3hwZ1drTEZHUHFS
            VzFBWGUxUkY1WER6cXd2Mmo0UFNDSGMKgy3pyLsAbL58rSRrR9E3aCIvrhoknRPZ
            /1NylAsuk6LNpB/oGg/BUPbMnVkTiHfP5pfiFfao7IQjlYRTG9iQLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:59:36Z"
    mac: ENC[AES256_GCM,data:X/RKnmUmHIexjr7t6aT2xZZ34mZXd/tbnjBESZ+VZOz7pkGuNOUniUbIRiRuhPynk+Rhg2FWG69yntfiBK36yU21HQ7wNfyJsGdXobmj6dkfUGmI+WRf8G+NfSqVs8z1h8vWsNuf8BHbyoxdFsChzxjLpJkL8jTKMJSAMCXNR68=,iv:ei0o1TVvzx9vt+be+dAXMWBcZzww7WyMWUbfZ8iDlSY=,tag:SYAnHWq8tpS9G5IP2wHUGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:1cu8rhlMt1GOn5jyyZ8kgyaV+/caAH2gfwc/RxAhmhr1MBhxE44+xiw6JftQiFfrvIgtNK/fZSDI+oibe9FdDshANKTdpdRm7kSbN+HsWOrqpEOvZwC5+v+0qRdfO0A0iBiAqVpMM2UPU3+WBojYio3Kf/C8ZNT0pENLfXtZI07DE5OKB/dxoml9EgObKs3jycakAD96XXS4aWFvvF0E7/9iwzAQkHayCnGxeeLNfRV/6OGJHLepGg==,iv:ZsZP8MwXJz1BMZhXMfzS0g0MhYVLZi0VvZ9BHqbLbwo=,tag:9yg78sx2TjCpdXxTGTqshA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VElUc0tYeFhPV1JHZTYw
            Z3VZZjJhWFdjYUxkUFEwOVpXQXZqZTlac0N3CkVLYVhyc0taamNwbzIvaDVJUFRO
            SDVuN0JWV0MzbUQxOThvZHJuSHRJbEkKLS0tIHFRR2kxM2JCb3hwZ1drTEZHUHFS
            VzFBWGUxUkY1WER6cXd2Mmo0UFNDSGMKgy3pyLsAbL58rSRrR9E3aCIvrhoknRPZ
            /1NylAsuk6LNpB/oGg/BUPbMnVkTiHfP5pfiFfao7IQjlYRTG9iQLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:59:36Z"
    mac: ENC[AES256_GCM,data:X/RKnmUmHIexjr7t6aT2xZZ34mZXd/tbnjBESZ+VZOz7pkGuNOUniUbIRiRuhPynk+Rhg2FWG69yntfiBK36yU21HQ7wNfyJsGdXobmj6dkfUGmI+WRf8G+NfSqVs8z1h8vWsNuf8BHbyoxdFsChzxjLpJkL8jTKMJSAMCXNR68=,iv:ei0o1TVvzx9vt+be+dAXMWBcZzww7WyMWUbfZ8iDlSY=,tag:SYAnHWq8tpS9G5IP2wHUGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
