apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NGZNdzJWdDRSYmxnb0xU
            Rk1NUzYzVEhKdFp6Vi95NFJhcWZGbEM0b0ZVCmV5ZmVRYy9VR05UWXVUdVVoMGlo
            cFRJNFdkZDJ5TE1scXhrVlI3MGZNL2MKLS0tIGd0c1ZWcjFqWUxSUzkyTGhsb2Vy
            RVRCcXBPQ1Jld1BCSCtKZ3pCeFFtbmsKCrKRqZAEhWgLv6f8NYOaHU9ZsbyMkX+X
            2CQBuLwF75bLqAPNNPOJkFF1JiKl4lHgKwYYGUa00k2EAbsnXskKxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:EEOfqvjlxbwT/reKVzViSE6bmNUzRXUTPd3yRfrff/9dc0+1nbJmsSg73jkqcQfaEdDA4o0XmoUQN+FfZR2fmYRTH34wmKlRFQVZe4B+XlJCugZ8xxqGUYlbxL6pGtMBpXNQrqHy5WrVttGJ03bfU5Bx80iW114y/XWxjvuKV7c=,iv:RKvjFtuf9Jm/zWJXCntG2YSz+0UzxSp+6FGR8bJP2V4=,tag:Zekd1fPXCuq8g3EhopQrEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:vrtqAmESTH+hJBEzr4V5BkFZlpJoFb5J4vbEBIDFeI7Wf3sehX9+SLg4uifvH/AfxlkEuRzg9e2Ke/p5vBQhBaGPARYYuhmelLQ0FOwPWAlpkpyGOUpce/BzG5OhCbp1XEPFKUGtMtm3Ja6Cz2wZ2c1itiEjRZxi2xrmN7UufBYRHLg0SlqGdZE5dGwsxJWAewJgrYVccWYEvtQWDhn75aAZ8LKz/S0cepjJiZ5AAxTBKT7X2TDKMw==,iv:XlffFLhBLOe/XX75PG4Wk8eNURxAHj5686GfjU/jUAc=,tag:Usp6DejaVzUU15cOy0LboA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NGZNdzJWdDRSYmxnb0xU
            Rk1NUzYzVEhKdFp6Vi95NFJhcWZGbEM0b0ZVCmV5ZmVRYy9VR05UWXVUdVVoMGlo
            cFRJNFdkZDJ5TE1scXhrVlI3MGZNL2MKLS0tIGd0c1ZWcjFqWUxSUzkyTGhsb2Vy
            RVRCcXBPQ1Jld1BCSCtKZ3pCeFFtbmsKCrKRqZAEhWgLv6f8NYOaHU9ZsbyMkX+X
            2CQBuLwF75bLqAPNNPOJkFF1JiKl4lHgKwYYGUa00k2EAbsnXskKxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:EEOfqvjlxbwT/reKVzViSE6bmNUzRXUTPd3yRfrff/9dc0+1nbJmsSg73jkqcQfaEdDA4o0XmoUQN+FfZR2fmYRTH34wmKlRFQVZe4B+XlJCugZ8xxqGUYlbxL6pGtMBpXNQrqHy5WrVttGJ03bfU5Bx80iW114y/XWxjvuKV7c=,iv:RKvjFtuf9Jm/zWJXCntG2YSz+0UzxSp+6FGR8bJP2V4=,tag:Zekd1fPXCuq8g3EhopQrEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
