---
# Plex config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
---
# Tautulli config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-config
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
