services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: ${MEDIA_PATH}
        target: /data
    restart: 'unless-stopped'
    environment:
      JELLYFIN_PublishedServerUrl: ${JELLYFIN_PublishedServerUrl:-}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    devices:
      - /dev/dri:/dev/dri
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    
      