services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/docker/gluetun:/gluetun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - DNS=${DNS}
      - SERVER_CITIES=${SERVER_CITIES}
      - WIREGUARD_MTU=1280
      - FIREWALL_VPN_INPUT_PORTS=55426,6881
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS:-}
    ports:
      - "9095:9095"       # qbittorrent
      - "6881:6881"       # qbittorrent
      - "6881:6881/udp"   # qbittorrent
      - "55426:55426"     # qbittorrent
      - "55426:55426/udp" # qbittorrent
      - "9000:9000"       # qbittorrent
      - "9000:9000/udp"   # qbittorrent
      - "7878:7878"       # radarr
      - "9696:9696"       # prowlarr
      - "8191:8191"       # flare solverr
      - "8989:8989"       # sonarr
      - "6767:6767"       # bazarr
    networks:
      - servarr_net
      - proxy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
      placement:
        constraints:
          - node.role == manager
      labels:
        caddy: qbittorrent.home sonarr.home radarr.home prowlarr.home bazarr.home
        caddy.qbittorrent.home.reverse_proxy: "{{upstreams 9095}}"
        caddy.sonarr.home.reverse_proxy: "{{upstreams 8989}}"
        caddy.radarr.home.reverse_proxy: "{{upstreams 7878}}"
        caddy.prowlarr.home.reverse_proxy: "{{upstreams 9696}}"
        caddy.bazarr.home.reverse_proxy: "{{upstreams 6767}}"
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - servarr_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=9095
      - UMASK_SET=022
    volumes:
      - /opt/docker/qbittorrent/config:/config
      - ${MEDIA_PATH}/downloads:/data/downloads
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    networks:
      - servarr_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/sonarr/config:/config
      - ${MEDIA_PATH}:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - servarr_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/radarr/config:/config
      - ${MEDIA_PATH}:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - servarr_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/prowlarr/config:/config
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/overseerr/config:/config
    ports:
      - "5055:5055"
    networks:
      - servarr_net
      - proxy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
      labels:
        caddy: overseerr.home
        caddy.reverse_proxy: "{{upstreams 5055}}"
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    networks:
      - servarr_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/bazarr/config:/config
      - ${MEDIA_PATH}:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    networks:
      - servarr_net
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped

networks:
  servarr_net:
    driver: overlay
    attachable: true
  proxy-net:
    external: true
    name: proxy-net

