services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/docker/gluetun:/gluetun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - DNS=${DNS}
      - SERVER_CITIES=${SERVER_CITIES}
      - WIREGUARD_MTU=1280
      - FIREWALL_VPN_INPUT_PORTS=55426,6881
      - FIREWALL_OUTBOUND_SUBNETS=${FIREWALL_OUTBOUND_SUBNETS:-}
    ports:
      - "9095:9095"       # qbittorrent
      - "6881:6881"       # qbittorrent
      - "6881:6881/udp"   # qbittorrent
      - "55426:55426"     # qbittorrent
      - "55426:55426/udp" # qbittorrent
      - "9000:9000"       # qbittorrent
      - "9000:9000/udp"   # qbittorrent
      - "7878:7878"       # radarr
      - "9696:9696"       # prowlarr
      - "8191:8191"       # flare solverr
      - "8989:8989"       # sonarr
      - 6767:6767         # bazarr
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}  
      - WEBUI_PORT=9095
      - UMASK_SET=022
    volumes:
      - /opt/qbittorrent/config:/config
      - ${MEDIA_PATH}/downloads:/data/downloads
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: service:gluetun
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/sonarr/config:/config
      - ${MEDIA_PATH}:/data
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/radarr/config:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/prowlarr/config:/config
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    container_name: overseerr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/overseerr/config:/config
    ports:
      - 5055:5055
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/bazarr/config:/config
      - ${MEDIA_PATH}:/data
    restart: unless-stopped
  flaresolverr:
    restart: unless-stopped
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
   

