apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcVQrM2xMWVdSWFZGR0wv
            a21nNmxFZEF1Ulh5SUFKd25lVkhidytqNm5NCm52NVoxSHFSQWtBVUVPeEc0UHVh
            cmI2NjNCWk4za3RpQ0svUG1YRUZRZVEKLS0tIDJQYUpIZDBFU1ZpeGRNcHpiS0dm
            QlM4S0sxMDdEbUxrbUxDenJ5KzF4bW8KR/fPoCxNtbBl1A4e9+27A65PeoW3gyGJ
            Mds0N/iCThwLRmtk9tcM+uZl4cTgNKdD81fSqxtqSiNr099UnHa3jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:vbAmocKwsVbdE0/71jx+LGooriDhs2mciA9vlsk/YYG7e0RMr/dg+Q9VdRaPhgWLld38rgfvVDFkBcyJb8O1ER+rphsssVXuvMrWrFKxDfkBR4cQ5XwmWhVsQHj66yL4JAU9hqdTP+PIE3VKmMAA9n+z3xokJWXGnUuTtyLeC1U=,iv:Z05oCdutQSUWJnEOKluZBYOI5f5XUAoG1aZIyd/TdNo=,tag:On5v8WITWKsCXsmebHEddw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:fueeXxtje9Rd9rAYoeshySJ/GjjSc8fPCDzVDWvSevSs6hMSK7ERoaroVTWF6AaGl3wHCQvrSpdkqMkmI0dEr/vO1bnEZJrh/MksN4erS7ojx7SWEeJ89Idk438HRCAapfqCPLKTAHOrxCkb/7Ccc4qsvq3HFH9sa3rT/7n2RbMQ71Myg3H/S5yeLNUffTv7GUW5yzPkbTjwpagCcYDw9vrQ4mB74852DFuua4MVg8OXNGl/I0rppw==,iv:gQwZZKzpAHJViGNAoAO5nh3WrJ8Hgpfyg1o5O0ussVI=,tag:EGRJT+pPcZdApXiwFk7tvQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcVQrM2xMWVdSWFZGR0wv
            a21nNmxFZEF1Ulh5SUFKd25lVkhidytqNm5NCm52NVoxSHFSQWtBVUVPeEc0UHVh
            cmI2NjNCWk4za3RpQ0svUG1YRUZRZVEKLS0tIDJQYUpIZDBFU1ZpeGRNcHpiS0dm
            QlM4S0sxMDdEbUxrbUxDenJ5KzF4bW8KR/fPoCxNtbBl1A4e9+27A65PeoW3gyGJ
            Mds0N/iCThwLRmtk9tcM+uZl4cTgNKdD81fSqxtqSiNr099UnHa3jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:vbAmocKwsVbdE0/71jx+LGooriDhs2mciA9vlsk/YYG7e0RMr/dg+Q9VdRaPhgWLld38rgfvVDFkBcyJb8O1ER+rphsssVXuvMrWrFKxDfkBR4cQ5XwmWhVsQHj66yL4JAU9hqdTP+PIE3VKmMAA9n+z3xokJWXGnUuTtyLeC1U=,iv:Z05oCdutQSUWJnEOKluZBYOI5f5XUAoG1aZIyd/TdNo=,tag:On5v8WITWKsCXsmebHEddw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
