apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-credential
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Gg5qqueHpfq+UlNSFXOV6eQsGmY=,iv:PNRjWCejU5Me3Y9JyThsqBPXpRbqYkfNZgxMVwlFydg=,tag:GS1msUaqvkcvo0a0UecQew==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bVW5HNuPAj9sJmbth27CUHgW/02LII4DWngeK5mpfTN0VBEEpQTxFw==,iv:4+C/LA5VtsD+SF3rkuPtkJnkfxFEfveQD1CqTWFD304=,tag:xHiLKbh1GOoOqQstMY3fBg==,type:str]
    #ENC[AES256_GCM,data:zPpmXB2RSLj+JSiObmmEbRfbYjXeA3eU00ok/3cN,iv:X7UM4ihMQRyChNonRitJ3RiO4WMRq7Vn6YXftaAAzEE=,tag:HvdXaXeJLxTkqMhwNgsGnQ==,type:comment]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:nkf9J9wuaAIq3iYu8yiToDa53X4cFV96yA==,iv:BY5tVrKuHhWoncH85/z0q6ntF/957dhVk3xtcoI8PF8=,tag:zp2b1wbYo0U2xWBK/DpGKw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cVdxZms4SFcvdm1KUStv
            RHBNd01tbjZCcGxZd253ZmhWQ3dRRDZDZXk4CjBFOHJsbW9HcWlBUmFPdHoxSis0
            T1Y4MzAwZVI1QkF2S1JVODFUUDdheDQKLS0tIHUzNi8xaHFYVklOSzRvY0JyOGo1
            RkVBSStLNktDQ1Rld09uelpnUVVLNmsKhaMaEt8ubIgeAmkLVcSF68FppIiYqtUx
            eAHqtie1usXE+7GjJS7zFOAK3jOwuxX9MsQqkCSbcPx+BGomGtxr0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:jF8Dynqa5zhghBkG194eUnDxEaAexrFZ3AVeFbNOgvSGTJighY+rqqPu/F5qahVLSSSCbJ5ydm3BfJuh9jZ3VdpmaGoC6U631H2xiAe/N5WoZA/YuF7cR97YV+YHNaWDD3q5l7bEiBHc2+119SSJsOmo9uhwGfXR5XZ5I84X8ME=,iv:SwoOeoTq2gFQx1VIOL8cIpWmX+xLboHDPWJHpOhNUXI=,tag:z0MDuIjwMBUbzWs760OyQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
