apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-credential
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:5d+lYLbgzNtdlsElbuWunRx1Tu0=,iv:uzdTvyw7xZSTA9itJCB6emE5PjGmcv7Uk70bkWPgBpA=,tag:JjIkW+pxddfSGx1fkstjVQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UkdQaZiz+N8VWrFa9Z+EFAwUJAClMxxyH9j1+cJSZW6UFTY1ZOZftg==,iv:8Lu/D85Ki7XKwps8FeMjfaYA4HNL02nvlS/HRjY9V7w=,tag:uWXE/aY5zRfYhgrogPmHoA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:bWbfEJhChxMsVHmvXPd93p2Q1o8VUvVxVQ==,iv:aUsvBQwBG/D7xCAFbrQXVK0GNjR6Sq2ghHg9bnVTukE=,tag:W513fL+fENNtqKmKVW4Jjg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OEVSMmVKU1NxR2NKSkx3
            eHB0aDZxaGY0a3NEeWU2eXF3RTNudGxiaTMwCmpjL0ZRY3ovOXduU1Jjcm9HdFVI
            dmNYdUVkTzZIOTN2TVlBVFFySVVndVkKLS0tIEgwd3N5bUZ5czBUd2huaXJuUEdw
            QXBnVlVGUkxoYTZmUVk0ZGMwSkRyUWMKS46TZQxArrJizZlfYWpmHJzr9UMOANAM
            y4YpO0Ra84JPnvANTBj6o1Qm7Sy0GveCT3I9ksE/gOuoVKGVtoSiLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T10:52:26Z"
    mac: ENC[AES256_GCM,data:f+MeZUQC2mEFbA5SyLmUMjubFw1s6yesS6dbZfp/mvFSyPNlgr2Yu8jLgW6kLdZ3PjG3AsTDr8H+Na67rGWEAW2DzYqBWbMos/uf0tNsVHy0YzK6vRFg6w3mWDU6KaIJK4lx8hCo0wsHXE557kOuY5OYIe9UH7gVf952IDfR8Vk=,iv:JWHwM6JAvp1/cGp0og/ayILiRf8UOJ8ps7gd9EG6iF8=,tag:LhDgUdURaKjOgxGqzLMbsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
