apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-credential
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bMjUrGCvIoOnRdvugC8fcs7i9MI=,iv:8+EX+trSD0fUfgFQCkUu50k/JHyntfXfpkKzBsA01vg=,tag:5eIikQKlXpivH51anj5cdg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cvDdDMQFxwj27rBHBcFR8r6QUduKgI99R2d4fwtHWowSjSzN6H1x2g==,iv:jhJPwCQI59on9xyVytXd0/PLBy+7KEL4Q5UWe8jYQ7c=,tag:jFB8fn7ctC9Alc37zgQAdw==,type:str]
    #ENC[AES256_GCM,data:rUoIG0aHQvSomwqC9acTb6qd45RbKNx/neSThlUE,iv:WuJr/Rem8I/8QIiywGqi/WsRsep/GaPCZmXVgIrWC30=,tag:Y9EbCmO1dC3e9LplmgxW2g==,type:comment]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OYNrPtinBnaeO4oFQwZ2iWAppRsVbNCeQw==,iv:AEa4MyS3q1yuq8lSZZOz/JaXs3E307p36Gf5Bi6emqY=,tag:bWQ/Ui9qcNt0AAdFHzRYFw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST3pYM0NlTXVQZDVzZDhL
            TlY5L0dxZjV1V1RwK1lkK3BaYnhTN2VpaUdnCldPVG91dnhwRWlsTFR2a0tSN2tz
            TzNtY3IrSVd3djRQWU5OMUlrRVNFY1UKLS0tIFVPSUFtMExyeElLOWh1YWY1SlpM
            Q3pWa3hhZXNzVGFUaVh5NUsvaW95UkEKRAzvOy4cIpBhgUeqFcu7qDbta97GBQdA
            HwZy0hK4WjgPzE4/YTRvv3Kxyw0RhwqXnp4VZ+YK54ly9CJvmVYHow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:55:36Z"
    mac: ENC[AES256_GCM,data:VgAbX7hehikxhReLRwBgeMfvCS7mXybgzrcKcwkPDBBo57GzkCBYqruBkSrFgWv1pUi0dXKpFtfWJDD0crAp1faW0s0qgN0HTxMbcyjO5tdluZ0LtzoaLaXhV3mfrYMC+5hjD8hgXB1borhOAwEihBoREaU+4jwp/lN10kwEVHY=,iv:857PabOWP2jAku/5W6h9yFNzuFmw7RN6UuBtqaf3AHc=,tag:/O5gfdAzUd+9f2VaQsGUBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
