apiVersion: v1
kind: Secret
metadata:
    name: cluster-settings
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ecJbrN1TtQ==,iv:xGW3XE9PPWRDsyB0Rzqkh2U1ys/isLFXruEYjVFhlzM=,tag:hcYqBJbTf6L/bF9KEgH6vQ==,type:str]
    SECRET_MAIN_NFS_IP: ENC[AES256_GCM,data:4ZgS0/3BSaBCq8by,iv:OeDQtiiSoqzr0HRbWyPFnmqCnFle/g2sLCi0Y8kMLbQ=,tag:U+FJElghMg7U3fBEiwH4JA==,type:str]
    SECRET_NAS_IP: ENC[AES256_GCM,data:tOhiofbIWZ7wzFwK,iv:CqObhwygWwVH7PR4fQik76+RMt9l/ULsTl7hP2yTQes=,tag:nj7ddYv5SfXHoOYeXt6OgA==,type:str]
    SECRET_METALLB_IP: ENC[AES256_GCM,data:xizJqFjMt5h07vTQ,iv:bDNCUTELC+qv5jSvjWJR4k0ziKrLEELTV8Kzc7oI4rM=,tag:+salQ7Hhlm9bNjYzK0L/Vw==,type:str]
    SECRET_PROXMOX_IP: ENC[AES256_GCM,data:GjSxs7PkTv+GsOk=,iv:WJkgOJ9E6ms7HYdVruNlBT2JN5tfMoaqRtBqV+ZgLq0=,tag:BYecqop1zQFBnYYxSmxm+g==,type:str]
    SECRET_HOMEASSISTANT_IP: ENC[AES256_GCM,data:qsNBVxh/KwPKr/Kd,iv:gv9JGOn15bhNId/1qQM/RuthORk1D85ZM7DxLN+oB3o=,tag:rIMLZ6RbkUvCjrF7rbAxDw==,type:str]
    SECRET_NET_LXC_IP: ENC[AES256_GCM,data:oOntoxcT77R8L2Qt,iv:0AgXOO8y7dw2mjmsiZmUXbWjJuSWoYh+OmFoBkF3nUo=,tag:VQxMMxkvgQkV2FSNghdPWg==,type:str]
    SECRET_VPS_IP: ENC[AES256_GCM,data:Y/l5yv0vJq8eh8GC,iv:iq2AVb2IGjMuk1cw7uOxxLgbkcOmDfi6JSPFPg8Q2lY=,tag:GhLCvuW5GFSCc/Mu1hIYmA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrai9XbUxsaEZQaGtGRXJr
            YmxOZG96WUNQZkh5TmxOOGYzNVR5SlZhK3lrCjlqYlBienBnTHAwNXAvbzBDZmI0
            ZnZ0b3JqK0N2UTVOejM5R1VOYUJoVGMKLS0tIEdhbUZrWWk1ODYwQWlHQ29TNXFt
            dDV2VGthOEVVbTJ2dDNyMFVuY2VWL0UKSvbs4JVqIz5C1zeX2Tq1qX0YajAI7HAr
            EqviOzbegXr38WwuQKThPBarQCtwaGNzUHuUq0iNDCzXlT66eqnVFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T20:26:35Z"
    mac: ENC[AES256_GCM,data:DVsZlFhgL7dWsK2nGapNVTrqW39wFCHqG3sg9EAZ5ffD5uVz/7Cukrc27xS9/a3HnYxZLGF5mFeoFznv10lFSNt9LVaw82bgNseuPJCLTvOR6sHoA/g14NyMo2zAPwol2j2w0dWdEQ1lqLZYNjTlsAey/wNWhio4GzMDOiW1YtA=,iv:aua8xUzZ2GH8z/wBGl7QqHuCWGTunnKEvRwcVPUvtXc=,tag:5o3uBlUmu0+SPT+EaGvzTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
