---
apiVersion: v1
kind: ConfigMap
metadata:
  name: servarr-config
  namespace: homelab
data:
  TZ: "Europe/Warsaw"
  PUID: "1000"
  PGID: "1000"
  MEDIA_PATH: "/mnt/media"
  WEBUI_PORT: "9095"
  UMASK_SET: "022"
  LOG_LEVEL: "info"
  LOG_HTML: "false"
  CAPTCHA_SOLVER: "none"
  # Gluetun VPN Configuration
  VPN_SERVICE_PROVIDER: "windscribe"
  VPN_TYPE: "wireguard"
  WIREGUARD_ADDRESSES: "100.99.14.211/32"
  DNS: "10.255.255.3"
  SERVER_CITIES: "Warsaw,London"
  WIREGUARD_MTU: "1280"
  FIREWALL_VPN_INPUT_PORTS: "55426,6881"
