---
apiVersion: v1
kind: Secret
metadata:
  name: servarr-secrets
  namespace: homelab
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: "key"
  WIREGUARD_PRESHARED_KEY: "key"
  FIREWALL_OUTBOUND_SUBNETS: ""
