apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mi7chal.dev@gmail.com # public dev email
    privateKeySecretRef:
      name: letsencrypt-dns-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-emoh-pl
  namespace: traefik-system
spec:
  secretName: wildcard-emoh-pl-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
    # Wildcard covers one level only
    - "s3.rustfs.${SECRET_DOMAIN}"
    - "*.s3.rustfs.${SECRET_DOMAIN}"
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
