services:
  adguardhome:
    image: adguard/adguardhome
    volumes:
      - /opt/docker/adguard/work:/opt/adguardhome/work
      - /opt/docker/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ}
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
      placement:
        constraints:
          - node.role == manager
      endpoint_mode: vip
    networks:
      - host
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/caddy/data:/data
    environment:
      - CADDY_INGRESS_NETWORKS=proxy-net
      - TZ=${TZ}
    networks:
      - proxy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
      placement:
        constraints:
          - node.role == manager
      labels:
        caddy.email: "admin@home"
  tailscale:
    image: tailscale/tailscale:latest
    hostname: home_server
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_ROUTES: ${TAILSCALE_ROUTES}
      TS_USERSPACE: false
      TS_EXTRA_ARGS: --snat-subnet-routes=true --accept-dns=false
      TZ: ${TZ}
    volumes:
      - /opt/docker/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - net_raw
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
      placement:
        constraints:
          - node.role == manager
      endpoint_mode: vip
    networks:
      - host
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
      TZ: ${TZ}
    networks:
      - cloudnet
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped

networks:
  cloudnet:
    driver: overlay
    attachable: true
  proxy-net:
    driver: overlay
    name: proxy-net
    attachable: true
  host:
    name: host
    external: true
