services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/docker/adguard/work:/opt/adguardhome/work
      - /opt/docker/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ}
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /opt/docker/nginx-proxy-manager/data:/data
      - /opt/docker/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: home_server
    network_mode: host
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_ROUTES: ${TAILSCALE_ROUTES}
      TS_USERSPACE: false
      TZ: ${TZ}
    volumes:
      - /opt/docker/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - net_raw
    restart: unless-stopped
